### PR TITLE
notification refactoring

### LINKED ISSUE #84: fix links in talkly mailbot
Acutally in info emails when something changed in a topic there is no link provided to jump directly to this topic

### PR DESCRIPTION
**Pull request by DavidBadura**
additionally fix #84

### CODE REVIEW

**Comment by tolry** [comment]
@DavidBadura could you tell me a bit about what refactorings you have done and why?

@smoench care to tell what you don't like about the refactoring and what you might have done differently?

**Comment by smoench** [comment]
this refactoring doesn't fix #84. only the use of the markdown twig filter for notification message subject in `src/AppBundle/Resources/views/Mail/notification.html.twig`  would fix it

**Comment by tolry** [comment]
@smoench Ok, as I get it, fixing #84 is a mere side effect of this MR, not the main focus, right?

@DavidBadura It would probably be good, if you could outline what changes you made and why.

**Comment by DavidBadura** [comment]
this PR **fix** the issue in #84 additionally, but as tobias said it is **not** the main focus. I have not claimed that it only fix this issue. The title says what this PR makes: "refactor notification system". I can split this in two separated PRs, but i wanted to save me the time.

In summary, i moved the notification out of symfony event namespace into an own `Notification` namespace. Now, the `NotificationManager` managed the transporter and the subscriber only receives the events and use the `NotificationManager` to send it out.

**Comment by DavidBadura** [comment]
ping ;-)

**Comment by tolry** [comment]
Heard no conclusive arguments against this merge and personally like the changes. Too much responsibilities split into to classes. Thanks @DavidBadura

**Pull request merged**
