### PR TITLE
[markdown] highlighting

### LINKED ISSUE #83: [markdown] code block preview
allow to use code block in markdown:

    ```
    echo 'hello world';
    ```

### PR DESCRIPTION
**Pull request by DavidBadura**
fix #83 

bildschirmfoto von 2016-08-22 12-19-41

### CODE REVIEW

**Comment by DavidBadura** [comment]
@tolry i have added a screenshot

**Comment by tolry** [comment]
language detection is done automatically or can be indicated?

**Comment by DavidBadura** [comment]
no, it isn't automatically. you have to specify it:

    ```js
    $(document).ready(function() {});
    ```

**Comment by tolry** [comment]
like that one better than automagic :wink:

**Pull request merged**
